repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: check-case-conflict
        name: pre-commit-hooks - Check for case conflicts
      - id: trailing-whitespace
        name: pre-commit-hooks - Trim Trailing Whitespace
      - id: end-of-file-fixer
        name: pre-commit-hooks - Fix End of Files
      - id: check-executables-have-shebangs
        name: pre-commit-hooks - Checks that non-binary executables have a proper shebang

  - repo: local
    hooks:
      - id: cppcheck
        name: C - cppcheck
        language: system
        stages: [commit]
        entry: cppcheck
        types: [c]
